# Generated by Django 6.0.3 on 2026-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('price', 'Price Alert'), ('restock', 'Restock Reminder'), ('supplier', 'New Supplier'), ('promo', 'Promotion'), ('system', 'System'), ('order', 'Order')], default='system', max_length=20),
        ),
    ]
