# Generated by Django 6.0.3 on 2026-04-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listingimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('forecast_month', models.DateField()),
                ('predicted_units', models.FloatField()),
                ('confidence', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-forecast_month', '-predicted_units'],
                'unique_together': {('city', 'category', 'forecast_month')},
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('month', models.DateField(db_index=True)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month', 'city', 'category'],
                'unique_together': {('city', 'category', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_ids', models.JSONField(default=list)),
                ('reasoning', models.TextField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('shopkeeper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_impact_summary', models.TextField()),
                ('best_city', models.CharField(max_length=255)),
                ('city_reasoning', models.TextField()),
                ('is_low_performing', models.BooleanField(default=False)),
                ('low_perf_guidance', models.TextField(blank=True)),
                ('portfolio_suggestions', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='listings.listing')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('listing', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('rank', models.PositiveSmallIntegerField()),
                ('units_sold', models.PositiveIntegerField()),
                ('month', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_rankings', to='listings.listing')),
            ],
            options={
                'ordering': ['city', 'rank'],
                'unique_together': {('city', 'listing', 'month')},
            },
        ),
    ]
