# Generated by Django 6.0.3 on 2026-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
