# Generated by Django 6.0.3 on 2026-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, default='', help_text='Firebase Cloud Messaging device token for push notifications', max_length=500),
        ),
    ]
