# Generated by Django 6.0.3 on 2026-03-31 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favouritesupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='RestockReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('bags', 'bags'), ('boxes', 'boxes'), ('cartons', 'cartons'), ('pieces', 'pieces'), ('liters', 'liters'), ('bottles', 'bottles')], default='kg', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
