# Generated by Django 6.0.3 on 2026-04-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_role_choices'),
        ('users', '0006_userprofile_verification_status'),
    ]

    operations = [
    ]
