# Generated by Django 6.0.3 on 2026-04-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_role_choices'),
        ('users', '0007_add_customer_role'),
    ]

    operations = [
    ]
