# Generated by Django 6.0.3 on 2026-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0003_update_role_choices_0007_add_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SHOPKEEPER', 'Shopkeeper'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
